package dev.moproco.icedlatte.domain;

public enum OrderStatus {
    CREATED, PENDING_PAYMENT, PAID, PROCESSING, SHIPPED, DELIVERED, CANCELLED, REFUND_REQUESTED, REFUNDED, PAYMENT_FAILED, PAYMENT_EXPIRED
}
