package dev.moproco.icedlatte.domain;

public enum PaymentStatus {
    CREATED, STRIPE_SESSION_CREATED, AWAITING_ASYNC_CONFIRMATION, PAID, FAILED, EXPIRED, REFUNDED, RECONCILIATION_FAILED, CANCELED, PROCESSING, REQUIRES_ACTION
}
